In [1]:
# !pip install torch cuda

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.9.0+cpu'

In [4]:
data = [[1, 2], [3, 4]]
np_data = np.array(data)
np_data

array([[1, 2],
       [3, 4]])

In [5]:
data

[[1, 2], [3, 4]]

In [6]:
type(np_data)

numpy.ndarray

In [7]:
type(data)

list

In [8]:
x_data = torch.tensor(data)

In [9]:
x_data

tensor([[1, 2],
        [3, 4]])

In [10]:
x_data

tensor([[1, 2],
        [3, 4]])

In [11]:
x_data_f = torch.FloatTensor(data)
x_data_f

tensor([[1., 2.],
        [3., 4.]])

In [12]:
print(x_data_f.dim)
print(x_data_f.shape)

<built-in method dim of Tensor object at 0x000001E4CDFAF340>
torch.Size([2, 2])


In [13]:
x_data_f[0][1]

tensor(2.)

In [14]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2,4]])
print(t1 + t2)

tensor([[3., 7.]])


In [15]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2]])
print(t1+t2)

tensor([[3., 5.]])


In [16]:
x_data_f.mean() # 1,2,3,4

tensor(2.5000)

In [17]:
x_data_f.mean(dim=0)
# 1 2
# 3 4

tensor([2., 3.])

In [18]:
x_data_f.mean(dim=1)
# 1 2
# 3 4

tensor([1.5000, 3.5000])

In [19]:
t1 = torch.FloatTensor([[1,3]])
t2 = torch.FloatTensor([[2,4]])

In [20]:
torch.cat([t1, t2], dim = 0)

tensor([[1., 3.],
        [2., 4.]])

In [21]:
torch.cat([t1, t2], dim = 1)

tensor([[1., 3., 2., 4.]])

In [22]:
t3 = torch.FloatTensor([[5,6]])
t4 = torch.stack([t1, t2, t3])
t4

tensor([[[1., 3.]],

        [[2., 4.]],

        [[5., 6.]]])

In [23]:
torch.ones_like(t4)


tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

In [24]:
torch.zeros_like(t4)


tensor([[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]])

In [25]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# y = 2x

In [26]:
# 가설 설정
# y = W * x + b
# 기존 사이킷런 머신 러닝: MSE 평균 제곱 오차

# cost funtion(비용함수) = loss function(손실함수) = error function(오차함수) = objective function(목적함수)
# 옵티마이져 (기울기가 제일 낮은 곳 , 경사 하강법(gradient descent) 사용) (Ex. 머신러닝에서 fit)

In [27]:
print(X_train.shape)
print(y_train.shape)

torch.Size([3, 1])
torch.Size([3, 1])


In [28]:
W = torch.zeros(1, requires_grad = True) # 바꿔가면서 쓸 변수다 .
# 기울기를 0으로 세팅
b = torch.zeros(1, requires_grad = True) # 바꿔가면서 쓸 변수다 .
# 바이어스 0으로 세팅

In [29]:
print(W)
print(b)


tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [30]:
# 현재 세팅 값 y = 0*x + 0

# 가설
hypothesis = X_train*W+b

In [31]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [32]:
cost = torch.mean((hypothesis - y_train)**2) # 원본값과 비교 / 평균ik 제곱 오차

In [33]:
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [34]:
# SGD 경사 하강법 적용 / lr 러닝 레이트가 너무 크면 빨리 찾아갈 수는 있지만 어디에 수렴하질 못함(발산한다) / 작게 잡으면 늦어질순 있지만 발산 정도는 낮아진다.
import torch.optim as optim
optimizer = optim.SGD([W, b], lr = 0.01)

In [35]:
# 0으로 시작하겠다
optimizer.zero_grad()

# 추적
cost.backward()

# 추적값 업데이트
optimizer.step()

In [36]:
# 종합

X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W, b], lr = 0.001)

# iter_ 값과 같은 반복요구값
nb_epochs = 20000
list_cost = []
for epoch in range(nb_epochs):
    hypothesis = X_train*W+b
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 중간마다 확인하고 싶다
    if epoch % 200 == 0:
        # list_cost.append(float(cost.item()))
        print('Epoch{:4d}/{} W: {:.3f}, b:{:.3f} , cost{:.5f}'.
             format( epoch, nb_epochs, W.item(), b.item(), cost.item()))
        
# import matplotlib.pyplot as plt
# print()
# plt.plot(range(100), list_cost)

Epoch   0/20000 W: 0.019, b:0.008 , cost18.66667
Epoch 200/20000 W: 1.513, b:0.624 , cost0.28531
Epoch 400/20000 W: 1.686, b:0.661 , cost0.06679
Epoch 600/20000 W: 1.717, b:0.637 , cost0.05845
Epoch 800/20000 W: 1.732, b:0.608 , cost0.05306
Epoch1000/20000 W: 1.745, b:0.579 , cost0.04820
Epoch1200/20000 W: 1.757, b:0.552 , cost0.04378
Epoch1400/20000 W: 1.768, b:0.526 , cost0.03976
Epoch1600/20000 W: 1.779, b:0.502 , cost0.03612
Epoch1800/20000 W: 1.790, b:0.478 , cost0.03281
Epoch2000/20000 W: 1.800, b:0.456 , cost0.02980
Epoch2200/20000 W: 1.809, b:0.434 , cost0.02707
Epoch2400/20000 W: 1.818, b:0.414 , cost0.02458
Epoch2600/20000 W: 1.826, b:0.394 , cost0.02233
Epoch2800/20000 W: 1.835, b:0.376 , cost0.02028
Epoch3000/20000 W: 1.842, b:0.358 , cost0.01842
Epoch3200/20000 W: 1.850, b:0.341 , cost0.01673
Epoch3400/20000 W: 1.857, b:0.325 , cost0.01520
Epoch3600/20000 W: 1.864, b:0.310 , cost0.01381
Epoch3800/20000 W: 1.870, b:0.296 , cost0.01254
Epoch4000/20000 W: 1.876, b:0.282 , cos

In [37]:
# 가설 설정
# y = W1 * x1 + W2 * x2 + W3 * x3 + b

# feature 가 3 개 , 포인트가 5개 / 결과값이 1개
X1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
X2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
X3_train = torch.FloatTensor([[75], [93], [90], [100], [73]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

W1 = torch.zeros(1, requires_grad = True)
W2 = torch.zeros(1, requires_grad = True)
W3 = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W1,W2,W3, b], lr = 0.000008)
nb_epochs = 200000
list_cost = []
for epoch in range(nb_epochs):
    hypothesis = X1_train*W1+X2_train*W2+X3_train*W3+b
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 중간마다 확인하고 싶다
    if epoch % 5000 == 0:
        # list_cost.append(float(cost.item()))
        print('Epoch : {:4d}/{} W1 : {:.3f}, W2 : {:.3f}, W3 : {:.3f}, b : {:.3f} , cost : {:.5f}'.
             format( epoch, nb_epochs, W1.item(),W2.item(),W3.item(), b.item(), cost.item()))

# 다변량에 있어서 0으로 수렴하기는 어렵다
# W1, W2, W3, b 값이 바뀌지 않고 일정할 때 만족하는 것이 좋다.

Epoch :    0/200000 W1 : 0.235, W2 : 0.235, W3 : 0.239, b : 0.003 , cost : 29661.80078
Epoch : 5000/200000 W1 : 0.733, W2 : 0.582, W3 : 0.691, b : 0.007 , cost : 0.47267
Epoch : 10000/200000 W1 : 0.762, W2 : 0.558, W3 : 0.686, b : 0.006 , cost : 0.43392
Epoch : 15000/200000 W1 : 0.779, W2 : 0.553, W3 : 0.674, b : 0.005 , cost : 0.42241
Epoch : 20000/200000 W1 : 0.792, W2 : 0.553, W3 : 0.662, b : 0.004 , cost : 0.41417
Epoch : 25000/200000 W1 : 0.804, W2 : 0.555, W3 : 0.649, b : 0.003 , cost : 0.40692
Epoch : 30000/200000 W1 : 0.814, W2 : 0.557, W3 : 0.637, b : 0.002 , cost : 0.40039
Epoch : 35000/200000 W1 : 0.824, W2 : 0.559, W3 : 0.625, b : 0.001 , cost : 0.39449
Epoch : 40000/200000 W1 : 0.833, W2 : 0.561, W3 : 0.614, b : -0.001 , cost : 0.38914
Epoch : 45000/200000 W1 : 0.842, W2 : 0.563, W3 : 0.604, b : -0.002 , cost : 0.38429
Epoch : 50000/200000 W1 : 0.850, W2 : 0.564, W3 : 0.594, b : -0.004 , cost : 0.37991
Epoch : 55000/200000 W1 : 0.858, W2 : 0.566, W3 : 0.584, b : -0.005 , c

In [38]:
# 간소화
import torch.nn as nn

In [39]:
model = nn.Linear(1,1) # (input_dim=1, output_dim=1)

In [40]:
print(list(model.parameters())) # 첫번째 텐서 = W , 두번째 텐서 = b

[Parameter containing:
tensor([[0.4195]], requires_grad=True), Parameter containing:
tensor([0.0167], requires_grad=True)]


In [41]:
optimizer = optim.SGD(model.parameters(), lr = 0.000001)

In [42]:
import torch.nn as nn
import torch.nn.functional as F

X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
model = nn.Linear(1,1) # (input_dim=1, output_dim=1)

print(list(model.parameters())) # 첫번째 텐서 = W , 두번째 텐서 = b

optimizer = optim.SGD(model.parameters(), lr = 0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(X_train)
    cost = F.mse_loss(prediction, y_train)   
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print('Epoch : {:4d}/{} loss : {:.5f}'.format(epoch, nb_epochs, cost.item()))

[Parameter containing:
tensor([[-0.9479]], requires_grad=True), Parameter containing:
tensor([0.3944], requires_grad=True)]
Epoch :    0/2000 loss : 36.05731
Epoch :  100/2000 loss : 0.17800
Epoch :  200/2000 loss : 0.10999
Epoch :  300/2000 loss : 0.06797
Epoch :  400/2000 loss : 0.04200
Epoch :  500/2000 loss : 0.02595
Epoch :  600/2000 loss : 0.01604
Epoch :  700/2000 loss : 0.00991
Epoch :  800/2000 loss : 0.00612
Epoch :  900/2000 loss : 0.00378
Epoch : 1000/2000 loss : 0.00234
Epoch : 1100/2000 loss : 0.00144
Epoch : 1200/2000 loss : 0.00089
Epoch : 1300/2000 loss : 0.00055
Epoch : 1400/2000 loss : 0.00034
Epoch : 1500/2000 loss : 0.00021
Epoch : 1600/2000 loss : 0.00013
Epoch : 1700/2000 loss : 0.00008
Epoch : 1800/2000 loss : 0.00005
Epoch : 1900/2000 loss : 0.00003
Epoch : 2000/2000 loss : 0.00002


In [43]:
new_input = torch.FloatTensor([[1.5]])
pred_y =model(new_input)
pred_y

tensor([[3.0039]], grad_fn=<AddmmBackward>)

In [2]:
import torch
import torch.nn.functional as F


In [3]:
z = torch.FloatTensor([1, 2, 3])

In [4]:
### Function Softmax
# K개의 값이 존재할 때 각각의 값의 편차를 확대시켜 
# 큰 값은 상대적으로 더 크게, 작은 값은 상대적으로 더 작게 만든 다음에 normalization 시키는 함수다

hypothesis = F.softmax(z, dim = 0)
hypothesis

# *** 지수 처리는 필수다.

tensor([0.0900, 0.2447, 0.6652])

In [5]:
import numpy as np
np.exp(1.0)/(np.exp(1.0) + np.exp(2.0) + np.exp(3.0))

0.09003057317038046

In [6]:
np.exp(2.0)/(np.exp(1.0) + np.exp(2.0) + np.exp(3.0))

0.24472847105479767

In [7]:
np.exp(3.0)/(np.exp(1.0) + np.exp(2.0) + np.exp(3.0))

0.6652409557748219

In [8]:
hypothesis.sum()

tensor(1.)

In [51]:
### MNIST

In [1]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import random

In [2]:
# !pip install torchvision

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
mnist_train = dsets.MNIST(root = 'MNIST_data/', train = True, transform = transforms.ToTensor(), 
                         download = True)
mnist_test = dsets.MNIST(root = 'MNIST_data/', train = False, transform = transforms.ToTensor(), 
                         download = True)

training_epochs = 15
batch_size = 100
data_loader = torch.utils.data.DataLoader(dataset = mnist_train,
                                         batch_size = batch_size,
                                         shuffle = True, drop_last = True)

C:\Users\CPB06GameN\anaconda3\lib\site-packages\torchvision\datasets\mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [5]:
mnist_train[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [6]:
image, label = mnist_train[0]
print(image.shape, label)

#### [흑백, 가로, 세로] 숫자 '5'

torch.Size([1, 28, 28]) 5


In [7]:
import matplotlib.pyplot as plt
import numpy as np

# plt.imshow(image.reshape(28, 28), cap = 'gray')

In [8]:
linear = nn.Linear( 28*28, 10, bias = True) # input_dim = 28*28, output_dim = 10

In [9]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.1)

In [10]:
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(data_loader)
    
    for X, y in data_loader:
        X = X.view(-1, 28*28)
        y = y
        
        hyphthesis = linear(X)
        cost = criterion(hyphthesis, y)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        avg_cost += cost/total_batch
        
    print('Epoch:', '%04d' %(epoch+1), 'cost=', "{:.9f}".format(avg_cost))

Epoch: 0001 cost= 0.534558892
Epoch: 0002 cost= 0.359259784
Epoch: 0003 cost= 0.331140339
Epoch: 0004 cost= 0.316343844
Epoch: 0005 cost= 0.307305545
Epoch: 0006 cost= 0.300468057
Epoch: 0007 cost= 0.294988215
Epoch: 0008 cost= 0.290935904
Epoch: 0009 cost= 0.287606329
Epoch: 0010 cost= 0.284453034
Epoch: 0011 cost= 0.281795233
Epoch: 0012 cost= 0.279786289
Epoch: 0013 cost= 0.277701825
Epoch: 0014 cost= 0.275894791
Epoch: 0015 cost= 0.274536222


In [13]:
with torch.no_grad():
    X_test = mnist_test.test_data.view(-1, 28*28).float()
    y_test = mnist_test.test_labels
    
    prediction = linear(X_test)
    
    correct_prediction = torch.argmax(prediction, 1) == y_test
    accuracy = correct_prediction.float().mean()
    print('acc:', accuracy.item())
    
    r = random.randint(0, len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1, 28*28).float()
    y_single_data = mnist_test.test_labels[r:r+1]
    print('label:', y_single_data.item())
    single_prediction = linear(X_single_data)
    print('Prediction:', torch.argmax(single_prediction, 1).item())
    
    #plt.imshow(mnist_test.test_data[r:r+1].view(28, 28), cmap = 'Greys', interpolation = 'nearest')
    #plt.show()

acc: 0.8835999965667725
label: 6
Prediction: 6


# Neural Network - DL

In [14]:
# Layering

# nn.Linear(784, 10)  784 -> 10
# 784 -> 256 -> 256 -> 10
linear1 = nn.Linear(784, 256)
linear2 = nn.Linear(256, 256)
linear3 = nn.Linear(256, 10)
relu = torch.nn.ReLU()    

## 미분에서 문제가 생길경우, relu 사용해보자 (이미지 작업)

In [15]:
# 초기화 작업
nn.init.normal_(linear1.weight)
nn.init.normal_(linear2.weight)
nn.init.normal_(linear3.weight)

Parameter containing:
tensor([[-1.7677e-01,  3.2348e-01,  2.6216e-01,  ...,  4.9912e-01,
         -5.6376e-01, -3.8905e-03],
        [ 2.8482e-01, -4.0620e-02, -1.2190e-01,  ...,  1.6252e+00,
          1.9711e-01, -7.0714e-01],
        [ 1.2289e-01,  3.9199e-01,  1.3049e-01,  ..., -3.2131e-01,
         -8.2046e-01,  5.0537e-01],
        ...,
        [ 7.8815e-01, -3.0617e+00,  1.6741e+00,  ...,  5.0366e-01,
          5.5795e-01,  1.8928e+00],
        [-6.2720e-01,  6.2964e-01, -1.3201e+00,  ...,  8.5647e-01,
         -4.1795e-01, -2.7260e+00],
        [-6.8437e-01, -1.0720e-01,  8.0460e-01,  ..., -3.2090e-01,
          2.3372e+00, -1.7617e-03]], requires_grad=True)

In [16]:
model = nn.Sequential(linear1, relu, linear2, relu, linear3)

In [18]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
total_batch = len(data_loader)
train_epochs = 15
batch_size = 100
for epoch in range(train_epochs):
    avg_cost = 0
    for X, y in data_loader:
        X = X.view(-1, 28 * 28)
        y = y
        optimizer.zero_grad()
        hyp = model(X)
        cost = criterion(hyp, y)
        cost.backward()
        optimizer.step()
        avg_cost += cost/total_batch
    print('Epoch:', '%04d' %(epoch+1), 'cost=', "{:.9f}".format(avg_cost))
    
print("End")

Epoch: 0001 cost= 175.037689209
Epoch: 0002 cost= 39.172035217
Epoch: 0003 cost= 24.402217865
Epoch: 0004 cost= 16.808706284
Epoch: 0005 cost= 12.226678848
Epoch: 0006 cost= 8.898686409
Epoch: 0007 cost= 6.709106922
Epoch: 0008 cost= 5.174489498
Epoch: 0009 cost= 3.785637140
Epoch: 0010 cost= 2.964432001
Epoch: 0011 cost= 2.214947701
Epoch: 0012 cost= 1.787160397
Epoch: 0013 cost= 1.454652429
Epoch: 0014 cost= 1.042757034
Epoch: 0015 cost= 0.831265807
End


In [81]:
with torch.no_grad():
    X_test = mnist_test.test_data.view(-1, 28*28).float()
    y_test = mnist_test.test_labels
    
    prediction = model(X_test)
    
    correct_prediction = torch.argmax(prediction, 1) == y_test
    accuracy = correct_prediction.float().mean()
    print('acc:', accuracy.item())
    
    r = random.randint(0, len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1, 28*28).float()
    y_single_data = mnist_test.test_labels[r:r+1]
    print('label:', y_single_data.item())
    single_prediction = model(X_single_data)
    print('Prediction:', torch.argmax(single_prediction, 1).item())
    
    #plt.imshow(mnist_test.test_data[r:r+1].view(28, 28), cmap = 'Greys', interpolation = 'nearest')
    #plt.show()

acc: 0.9467999935150146
label: 1
Prediction: 1
