In [2]:
from sklearn.datasets import load_files

In [29]:
reviews_train = load_files("aclImdb/train")

In [30]:
text_train, y_train = reviews_train.data, reviews_train.target
text_train[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [31]:
len(text_train)

25000

In [32]:
text_train = [a_review.replace(b"<br />", b" ") for a_review in text_train]

In [8]:
import numpy as np
import pandas as pd
np.bincount(y_train)

array([12500, 12500, 50000], dtype=int64)

In [33]:
reviews_test = load_files("aclImdb/test")
text_test, y_test = reviews_test.data, reviews_test.target


In [34]:
np.bincount(y_test)

array([12500, 12500], dtype=int64)

In [35]:
text_test = [a_review.replace(b"<br />", b" ") for a_review in text_test]

In [36]:
bards_words = ["The fool doth think he is wise,", "but the wise man knows himself to be a fool"]

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer().fit(bards_words)

In [38]:
# 단어를 고유한 숫자로 표현
vect.vocabulary_

{'the': 9,
 'fool': 3,
 'doth': 2,
 'think': 10,
 'he': 4,
 'is': 6,
 'wise': 12,
 'but': 1,
 'man': 8,
 'knows': 7,
 'himself': 5,
 'to': 11,
 'be': 0}

In [39]:
bag_of_words = vect.transform(bards_words)
bag_of_words.toarray()
### 사용 빈도
### 첫번째 문장 [be 0번, but 0번, doth 1번 .....], 
###  두번째 문장 [be 1번, but 1번 ....... wise 1번 ]

array([[0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1]], dtype=int64)

In [40]:
vect = CountVectorizer().fit(text_train)
X_train = vect.transform(text_train)
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [41]:
feature_names = vect.get_feature_names()

In [42]:
len(feature_names)

74849

In [43]:
feature_names[:20]

['00',
 '000',
 '0000000000001',
 '00001',
 '00015',
 '000s',
 '001',
 '003830',
 '006',
 '007',
 '0079',
 '0080',
 '0083',
 '0093638',
 '00am',
 '00pm',
 '00s',
 '01',
 '01pm',
 '02']

In [44]:
feature_names[20000:20010]

['draper',
 'draperies',
 'drapery',
 'drapes',
 'draskovic',
 'drastic',
 'drastically',
 'drat',
 'dratch',
 'dratic']

In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

scores = cross_val_score(
    LogisticRegression(max_iter=1000), 
    X_train, y_train, cv=5
) 
scores

array([0.8824, 0.876 , 0.882 , 0.8884, 0.8776])

In [46]:
X_test =vect.transform(text_test)

In [47]:
lr = LogisticRegression(max_iter=1000).fit(X_train, y_train)

In [48]:
y_pred = lr.predict(X_test[15500])

In [49]:
y_pred[0]

0

In [50]:
y_test[15500]

0

In [51]:
text_test[15500]

b'Do the writers that conjure up these type of "comedies" have such empty lives that they have to embody them in tragic shows like this?.  Why the talented and gorgeous Busy Phillips is amongst this trash is beyond me,I cannot stand the Hispanic girl whose accent sounds very fake and is so unfunny and annoying as is the other African-American girl with the shrill voice.  The jokes are often stupid, the Jewish guy yells a lot and the show never goes anywhere, one particular episode with the solider looking for love was just terrible.  I don\'t believe there would be that many working in a looking for love office and only one man? Of course all of the Woman are in tight fitting tops and tons of make up to make up for their lack of talent.  I actually found Holly funny in her older shows and I have always admired Busy but this show is dumb, empty and had nothing going for it.'