In [2]:
import numpy as np
my_arr = np.arange(1000000)              # numpy로 만들기
my_list = list(range(1000000))            # python 내장함수로 만들기
%time for i in range(10): my_arr2=my_arr*2


Wall time: 13.9 ms


In [3]:
%time for i in range(10): my_list2=[x * 2 for x in my_list]

Wall time: 723 ms


In [4]:
723 / 13.9                       # numpy 속도가 52배 빠름

52.014388489208635

In [21]:
# Numpy ndarray : 다차원 배열 객체
data = np.random.randn(2, 3)                            # 2행 3열의 데이터를 만들어라
print(data)

[[ 0.06732238  0.74440746  1.17666355]
 [ 0.02514417 -2.69684771  0.22399884]]


In [22]:
data * 10

array([[  0.67322378,   7.44407465,  11.7666355 ],
       [  0.2514417 , -26.96847709,   2.23998843]])

In [23]:
data + data

array([[ 0.13464476,  1.48881493,  2.3533271 ],
       [ 0.05028834, -5.39369542,  0.44799769]])

In [24]:
data.dtype

dtype('float64')

In [25]:
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
data2d = [[1,2,3,4], [5,6,7,8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [32]:
arr2d = np.array(data2d)            # 다차원으로 만들어주기

In [33]:
arr2d.ndim                          # 2차원

2

In [34]:
arr2d.shape                         # 2행 4열로 결과값 출력

(2, 4)

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3, 6))                     # 튜플로 묶어주면 1개의 값만 입력 


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
np.zeros((4,3,2))                    # 3행 2열 데이터를 4개의 층으로 출력 => (4, 3, 2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [42]:
np.zeros((4,3,2)).dtype

dtype('float64')

In [49]:
arr = np.zeros((4,3,2), dtype=np.int32)
arr.dtype

dtype('int32')

In [55]:
arr1 = np.zeros((2, 3))
arr2 = np.ones_like(arr1)
arr2.shape
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
arr3 = np.full((2,3), 5)                    # 2행 3열의 데이터에 5라는 값으로 채우고싶음
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [62]:
arr4 = np.eye(3)                            # 단위행렬(E) 만들기
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])